from ModelManagement.Util.keras_util import *


class MobileNet_V1(tf.keras.models.Model):

    def __init__(self, classes, first_channel=32, **kwargs):
        super(MobileNet_V1, self).__init__(**kwargs)

        self.model_name = 'MobileNet_V1'

        channels = (
        first_channel, first_channel * 2, first_channel * 4, first_channel * 8, first_channel * 16, first_channel * 32)

        self.conv_0 = set_conv(channels[0], kernel=(3, 3), strides=(2, 2), name='conv_0')
        self.bn_0 = set_batch_normalization(name='bn_0')

        self.depth_conv_1 = set_depthwise_conv(kernel=(3, 3), name='depth_conv_1')
        self.depth_bn_1 = set_batch_normalization(name='depth_bn_1')
        self.point_conv_1 = set_conv(channels[1], kernel=(1, 1), name='point_conv_1')
        self.point_bn_1 = set_batch_normalization(name='point_bn_1')

        self.depth_conv_2 = set_depthwise_conv(kernel=(3, 3), strides=(2, 2), name='depth_conv_2')
        self.depth_bn_2 = set_batch_normalization(name='depth_bn_2')
        self.point_conv_2 = set_conv(channels[2], kernel=(1, 1), name='point_conv_2')
        self.point_bn_2 = set_batch_normalization(name='point_bn_2')

        self.depth_conv_3 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_3')
        self.depth_bn_3 = set_batch_normalization(name='depth_bn_3')
        self.point_conv_3 = set_conv(channels[2], kernel=(1, 1), name='point_conv_3')
        self.point_bn_3 = set_batch_normalization(name='point_bn_3')
        self.depth_conv_4 = set_depthwise_conv(kernel=(3, 3), strides=(2, 2), name='depth_conv_4')
        self.depth_bn_4 = set_batch_normalization(name='depth_bn_4')
        self.point_conv_4 = set_conv(channels[3], kernel=(1, 1), name='point_conv_4')
        self.point_bn_4 = set_batch_normalization(name='point_bn_4')

        self.depth_conv_5 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_5')
        self.depth_bn_5 = set_batch_normalization(name='depth_bn_5')
        self.point_conv_5 = set_conv(channels[3], kernel=(1, 1), name='point_conv_5')
        self.point_bn_5 = set_batch_normalization(name='point_bn_5')
        self.depth_conv_6 = set_depthwise_conv(kernel=(3, 3), strides=(2, 2), name='depth_conv_6')
        self.depth_bn_6 = set_batch_normalization(name='depth_bn_6')
        self.point_conv_6 = set_conv(channels[4], kernel=(1, 1), name='point_conv_6')
        self.point_bn_6 = set_batch_normalization(name='point_bn_6')

        self.depth_conv_7 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_7')
        self.depth_bn_7 = set_batch_normalization(name='depth_bn_7')
        self.point_conv_7 = set_conv(channels[4], kernel=(1, 1), name='point_conv_7')
        self.point_bn_7 = set_batch_normalization(name='point_bn_7')
        self.depth_conv_8 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_8')
        self.depth_bn_8 = set_batch_normalization(name='depth_bn_8')
        self.point_conv_8 = set_conv(channels[4], kernel=(1, 1), name='point_conv_8')
        self.point_bn_8 = set_batch_normalization(name='point_bn_8')
        self.depth_conv_9 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_9')
        self.depth_bn_9 = set_batch_normalization(name='depth_bn_9')
        self.point_conv_9 = set_conv(channels[4], kernel=(1, 1), name='point_conv_9')
        self.point_bn_9 = set_batch_normalization(name='point_bn_9')
        self.depth_conv_10 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_10')
        self.depth_bn_10 = set_batch_normalization(name='depth_bn_10')
        self.point_conv_10 = set_conv(channels[4], kernel=(1, 1), name='point_conv_10')
        self.point_bn_10 = set_batch_normalization(name='point_bn_10')
        self.depth_conv_11 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_11')
        self.depth_bn_11 = set_batch_normalization(name='depth_bn_11')
        self.point_conv_11 = set_conv(channels[4], kernel=(1, 1), name='point_conv_11')
        self.point_bn_11 = set_batch_normalization(name='point_bn_11')

        self.depth_conv_12 = set_depthwise_conv(kernel=(3, 3), strides=(2, 2), name='depth_conv_12')
        self.depth_bn_12 = set_batch_normalization(name='depth_bn_12')
        self.point_conv_12 = set_conv(channels[5], kernel=(1, 1), name='point_conv_12')
        self.point_bn_12 = set_batch_normalization(name='point_bn_12')

        self.depth_conv_13 = set_depthwise_conv(kernel=(3, 3), strides=(1, 1), name='depth_conv_13')
        self.depth_bn_13 = set_batch_normalization(name='depth_bn_13')
        self.point_conv_13 = set_conv(channels[5], kernel=(1, 1), name='point_conv_13')
        self.point_bn_13 = set_batch_normalization(name='point_bn_13')

        self.gap = set_global_average_pooling()
        self.fcl = set_dense(channel=classes, name='fcl', activation='softmax')

    def call(self, inputs, training):
        net = self.conv_0(inputs)
        net = self.bn_0(net, training)
        net = set_relu6(net)

        net = self.depth_conv_1(net)
        net = self.depth_bn_1(net, training)
        net = set_relu6(net)
        net = self.point_conv_1(net)
        net = self.point_bn_1(net, training)
        net = set_relu6(net)
        net = self.depth_conv_2(net)
        net = self.depth_bn_2(net, training)
        net = set_relu6(net)
        net = self.point_conv_2(net)
        net = self.point_bn_2(net, training)
        net = set_relu6(net)
        net = self.depth_conv_3(net)
        net = self.depth_bn_3(net, training)
        net = set_relu6(net)
        net = self.point_conv_3(net)
        net = self.point_bn_3(net, training)
        net = set_relu6(net)
        net = self.depth_conv_4(net)
        net = self.depth_bn_4(net, training)
        net = set_relu6(net)
        net = self.point_conv_4(net)
        net = self.point_bn_4(net, training)
        net = set_relu6(net)
        net = self.depth_conv_5(net)
        net = self.depth_bn_5(net, training)
        net = set_relu6(net)
        net = self.point_conv_5(net)
        net = self.point_bn_5(net, training)
        net = set_relu6(net)
        net = self.depth_conv_6(net)
        net = self.depth_bn_6(net, training)
        net = set_relu6(net)
        net = self.point_conv_6(net)
        net = self.point_bn_6(net, training)
        net = set_relu6(net)
        net = self.depth_conv_7(net)
        net = self.depth_bn_7(net, training)
        net = set_relu6(net)
        net = self.point_conv_7(net)
        net = self.point_bn_7(net, training)
        net = set_relu6(net)
        net = self.depth_conv_8(net)
        net = self.depth_bn_8(net, training)
        net = set_relu6(net)
        net = self.point_conv_8(net)
        net = self.point_bn_8(net, training)
        net = set_relu6(net)
        net = self.depth_conv_9(net)
        net = self.depth_bn_9(net, training)
        net = set_relu6(net)
        net = self.point_conv_9(net)
        net = self.point_bn_9(net, training)
        net = set_relu6(net)
        net = self.depth_conv_10(net)
        net = self.depth_bn_10(net, training)
        net = set_relu6(net)
        net = self.point_conv_10(net)
        net = self.point_bn_10(net, training)
        net = set_relu6(net)
        net = self.depth_conv_11(net)
        net = self.depth_bn_11(net, training)
        net = set_relu6(net)
        net = self.point_conv_11(net)
        net = self.point_bn_11(net, training)
        net = set_relu6(net)
        net = self.depth_conv_12(net)
        net = self.depth_bn_12(net, training)
        net = set_relu6(net)
        net = self.point_conv_12(net)
        net = self.point_bn_12(net, training)
        net = set_relu6(net)
        net = self.depth_conv_13(net)
        net = self.depth_bn_13(net, training)
        net = set_relu6(net)
        net = self.point_conv_13(net)
        net = self.point_bn_13(net, training)
        net = set_relu6(net)

        net = self.gap(net)
        net = self.fcl(net)
        return net

    def get_name(self):
        return self.model_name
